### PR TITLE
fixed notification drawer and added view request

### LINKED ISSUE #73: Fix Notification Drawer
Task 1: 
View Request does not have anything setup for it. Please reference this Figma: (https://www.figma.com/file/VkH80LtHkl1Ck76v88fTvk/FPH-Wireframes?type=design&node-id=3329-9453&mode=design&t=JdGksYsWMHWTJH03-0). This will tie into Task 2 where you click on View Supply Request from the Notification Drawer. So make sure to setup localhost:3000/ViewSupplyRequest/{SupplyRequestId} such that when we visit this URL, we do a GET request on the NotificationId = SupplyRequestId and then parse the message column into the text fields like so: 
image

Also note that the message column, that every message is going to be formatted in this exact way: 
image

Where "Business ID:{BusinessId}" is the first thing. This will be how we get the Business ID that we can leverage for the hyperlink 
image. 

Do not setup this thing:
image

Task 2:
Figma: https://www.figma.com/file/VkH80LtHkl1Ck76v88fTvk/FPH-Wireframes?type=design&node-id=2496-24075&mode=design&t=JdGksYsWMHWTJH03-0

Last time you guys setup the Notification drawer, but now set it up so that the buttons actually work when you press on it. We have setup the intermeditary tasks that have URLs for View Information, Download CSV, View Application, as well as View Supply Request.

### PR DESCRIPTION
**Pull request by srukelman**
closes #73

### CODE REVIEW

File: src/components/ViewRequest/ViewRequest.jsx [hunk 1]
```diff
@@ -0,0 +1,197 @@
...
+            setBusinessName(businessResponse.data[0].name);
+        }
+        catch(error){
+            console.error(error);
+        }
+        
+    }
+    useEffect(() => {
+        fetchRequest();
+    }, [id]);
```
Comment (ctc-devops) [inline src/components/ViewRequest/ViewRequest.jsx:68]: ⚠️ **[eslint]** <[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>React Hook useEffect has a missing dependency: 'fetchRequest'. Either include it or remove the dependency array.
